version: 2
env:
  - GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  - DOCKER_BUILDKIT: "1"  # Make sure all values are strings

before:
  hooks:
    - go mod tidy
    - make web
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    main: ./cmd/premiumizearrd
    ldflags:
      - '-extldflags "-static"'
    flags:
      - '-tags=netgo,osusergo' # Add build tags
    binary: premiumizearrd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - src: build/*.service
        dst: ./
        strip_parent: true
      - src: build/static/*
        dst: static
        strip_parent: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    package_name: premiumizearr
    bindir: /opt/premiumizearrd
    vendor: Philipp Ensinger
    homepage: https://github.com/ensingerphilipp/premiumizearr-nova
    maintainer: Philipp <philippensi2@gmail.com>
    description: Service to connect premiumize.me to Arr clients.
    license: GPLv3
    formats:
      - deb
    contents:
      - src: build/static/*
        dst: /opt/premiumizearrd/static/
      - src: init/premiumizearrd.service
        dst: /etc/systemd/system/premiumizearrd.service
    scripts:
      postinstall: "scripts/postinstall.sh"
      
dockers:
  -
    use: docker
    goos: linux
    goarch: amd64
    image_templates:
    - "ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-amd64"
    skip_push: "false"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=\"https://github.com/ensingerphilipp/premiumizearr-nova\""
    - "--platform=linux/amd64"
    dockerfile: "docker/Dockerfile.amd64"
    extra_files:
    - build/static/
    - docker/
  -
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-arm64"
    skip_push: "false"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=\"https://github.com/ensingerphilipp/premiumizearr-nova\""
    - "--platform=linux/arm64"
    dockerfile: "docker/Dockerfile.arm64"
    extra_files:
    - build/static/
    - docker/
  -
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-armv7"
    skip_push: "false"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=\"https://github.com/ensingerphilipp/premiumizearr-nova\""
    - "--platform=linux/arm/v7"
    dockerfile: "docker/Dockerfile.armv7"
    extra_files:
    - build/static/
    - docker/

docker_manifests:
  - skip_push: false
  - name_template: 'ghcr.io/ensingerphilipp/premiumizearr-nova:dev'
    image_templates:
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-amd64'
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-armv7'
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}'
    image_templates:
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-amd64'
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-armv7'
    - 'ghcr.io/ensingerphilipp/premiumizearr-nova:{{ .Tag }}-arm64'

release:
  prerelease: true
  header: "Premiumizearr Pre-Release {{ .Tag }}"
  footer: "**Full Changelog**: https://github.com/ensingerphilipp/premiumizearr-nova/compare/{{ .PreviousTag }}...{{ .Tag }}"


